name: Create PR to Develop

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create_pr_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}  # A branch de onde o PR será criado
          base: develop  # A branch para onde o PR será criado
          title: "Automatically created PR from feature branch"
