name: Create PR
on: 
  push:
    branches: 
      - "feature/*"
  workflow_run:
    workflows: [".NET Core Desktop"]
    types:
      - completed

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "An automatically created PR!"
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        base: develop